/* Presentation-only placeholders. No drafting engine, body data or fit claims. */
const chapterNames = ['Opening image','The project','Body & measurement','Rules to geometry','Block to princess line','An open system','Pattern to style','Body × design','Circular runway','Outcome explorer','Physical studies','The outcome matrix','Conclusion & credits','Closing image'];
const sections = [...document.querySelectorAll('main > section')];
document.querySelector('#chapter-menu').innerHTML = sections.map((section,i)=>`<a href="#${section.id}"><span>${String(i+1).padStart(2,'0')}</span>${chapterNames[i]}</a>`).join('');
const menuButton=document.querySelector('#menu-toggle'), menu=document.querySelector('#chapter-menu');
function closeMenu(){menu.hidden=true;menuButton.setAttribute('aria-expanded','false');}
menuButton.addEventListener('click',()=>{menu.hidden=!menu.hidden;menuButton.setAttribute('aria-expanded',String(!menu.hidden));});
menu.addEventListener('click',e=>{if(e.target.closest('a'))closeMenu();});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMenu();menuButton.focus();}});

function model(index=0){const flare=[29,40,49,34,45,55][index%6];return `<svg class="model" viewBox="0 0 120 320" aria-hidden="true"><ellipse cx="60" cy="29" rx="13" ry="18" fill="currentColor" opacity=".6"/><path d="M53 47L52 59 35 69 29 111 19 153M67 47L68 59 85 69 92 111 101 153" fill="none" stroke="currentColor" stroke-width="6" stroke-linecap="round"/><path d="M42 65Q60 76 78 65L75 113Q74 128 80 145L${60+flare} 249Q60 263 ${60-flare} 249L40 145Q46 128 45 113Z" fill="currentColor" fill-opacity=".45" stroke="currentColor" stroke-width="1.2"/><path d="M52 73Q59 109 50 145L43 252M68 73Q61 109 70 145L77 252" fill="none" stroke="currentColor" opacity=".75"/><path d="M48 257L46 302 38 309M72 257L75 302 83 309" fill="none" stroke="currentColor" stroke-width="5" stroke-linecap="round"/></svg>`;}
function pattern(index=0){const f=[0,12,24,8][index%4];return `<svg class="pattern" viewBox="0 0 330 390" aria-hidden="true"><g class="guide"><path d="M10 70H320M10 145H320M10 220H320M10 355H320M50 25V370M170 25V370M275 25V370"/></g><path d="M32 65L55 40Q66 66 81 61L84 101Q76 125 80 146L${91+f} 355L25 355L32 65Z"/><path d="M104 65L127 48Q121 85 135 99L132 145L${147+f} 352L${100-f/3} 355L111 147Q118 102 104 65Z"/><path d="M170 48L192 61Q179 89 187 103L181 147L${195+f} 355L${151-f/4} 352L161 145Q164 115 156 99Z"/><path d="M214 62Q235 72 246 42L271 65L281 355L${211-f/2} 355L220 145Q228 109 214 62Z"/><g class="guide"><path d="M55 96V323M121 177V320M172 182V320M248 96V323"/><path d="M51 103L55 95 59 103M117 184L121 176 125 184M168 189L172 181 176 189M244 103L248 95 252 103"/></g><g fill="currentColor" stroke="none"><circle cx="81" cy="61" r="2"/><circle cx="132" cy="145" r="2"/><circle cx="181" cy="147" r="2"/><circle cx="220" cy="145" r="2"/></g></svg>`;}
document.querySelectorAll('[data-models]').forEach(el=>el.innerHTML=Array.from({length:Number(el.dataset.models)},(_,i)=>model(i)).join(''));
document.querySelectorAll('[data-pattern]').forEach(el=>el.innerHTML=pattern(Number(el.dataset.pattern)));
document.querySelectorAll('[data-photo-strip]').forEach(el=>el.innerHTML=el.dataset.photoStrip.split('|').map((name,i)=>`<div class="media">${model(i)}<span>${name} / Photo placeholder</span></div>`).join(''));
document.querySelectorAll('[data-pattern-strip]').forEach(el=>el.innerHTML=el.dataset.patternStrip.split('|').map((name,i)=>`<figure>${pattern(i)}<figcaption class="caption">${name}<b>0${i+1} ↗</b></figcaption></figure>`).join(''));

const garmentOptions=document.querySelector('#garment-options');
garmentOptions.innerHTML=Array.from({length:4},(_,i)=>`<button class="garment-option ${i===0?'active':''}" data-form="${i}" aria-pressed="${i===0}">${model(i)}<span>Form 0${i+1}</span></button>`).join('');
function selectForm(index){document.querySelector('#selected-pattern').innerHTML=pattern(index);document.querySelector('#variation-pattern').innerHTML=pattern(index)+pattern(index)+pattern(index);document.querySelector('#selected-pattern-label').textContent=`Pattern / Form 0${index+1}`;garmentOptions.querySelectorAll('button').forEach((b,i)=>{b.classList.toggle('active',i===index);b.setAttribute('aria-pressed',String(i===index));});}
garmentOptions.querySelectorAll('button').forEach((button,i)=>['pointerenter','focus','click'].forEach(event=>button.addEventListener(event,()=>selectForm(i))));selectForm(0);
const fittingGroups=document.querySelector('#fitting-groups');
fittingGroups.innerHTML=Array.from({length:4},(_,i)=>`<button class="fitting-group" aria-pressed="false"><div class="media">${model(i)}${model(i+1)}</div><span class="caption">Study 0${i+1} / Fitting photo group</span></button>`).join('');
function selectFitting(index){fittingGroups.querySelectorAll('button').forEach((b,i)=>{b.classList.toggle('active',i===index);b.setAttribute('aria-pressed',String(i===index));});document.querySelector('#fitting-detail-a span').textContent=`Seam detail / Study 0${index+1}`;document.querySelector('#fitting-detail-b span').textContent=`Movement detail / Study 0${index+1}`;document.querySelector('#fitting-detail-a').style.background=['#d5d5d5','#c8c8c8','#cccccc','#c5c5c5'][index];document.querySelector('#fitting-detail-b').style.background=['#e1e1e1','#dcdcdc','#e0e0e0','#d7d7d7'][index];document.querySelector('#fitting-caption').textContent=`Study 0${index+1} / Fitting photographs and observations to be added.`;}
fittingGroups.querySelectorAll('button').forEach((button,i)=>['pointerenter','focus','click'].forEach(event=>button.addEventListener(event,()=>selectFitting(i))));selectFitting(0);

// Illustrative positions only. Replace with real body/profile × design coordinates later.
const positions=[{x:15,y:28,body:'A',design:'01'},{x:35,y:38,body:'B',design:'02'},{x:55,y:14,body:'A',design:'03'},{x:75,y:45,body:'C',design:'04'},{x:85,y:30,body:'B',design:'05'}];
const cast=document.querySelector('#matrix-cast');
cast.innerHTML=positions.map((p,i)=>`<button class="matrix-model" style="--home:${10+i*20}%;--target-x:${p.x}%;--target-y:${p.y}%" aria-label="Locate model ${i+1}: body ${p.body}, design ${p.design}" aria-pressed="false">${model(i)}<span>0${i+1}</span></button>`).join('');
// Keep the location marker in the figure's coordinate space, directly at its feet.
cast.append(document.querySelector('#matrix-point'));
function locate(index){cast.querySelectorAll('button').forEach((button,i)=>{button.classList.toggle('active',i===index);button.setAttribute('aria-pressed',String(i===index));});const p=positions[index];document.querySelector('#matrix-caption').textContent=`Model 0${index+1} / Body ${p.body} × Design ${p.design}`;const point=document.querySelector('#matrix-point');point.style.opacity='1';point.style.left=`${p.x}%`;point.style.top=`calc(${p.y}% + var(--figure-feet))`;}
cast.querySelectorAll('button').forEach((button,i)=>['pointerenter','focus','click'].forEach(event=>button.addEventListener(event,()=>locate(i))));
document.querySelector('#matrix-reset').addEventListener('click',()=>{cast.querySelectorAll('button').forEach(button=>{button.classList.remove('active');button.setAttribute('aria-pressed','false');});document.querySelector('#matrix-point').style.opacity='0';document.querySelector('#matrix-caption').textContent='Select a model / explore the matrix';});
